version: '3.1'
services:
  database:
    image: "postgres"
    ports:
      - "5432:5434"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=postgres
  web:
#    container_name: app-springboot-postgresql
#    image: app-springboot-postgresql
    image: zoho-replica
#    build: .
    ports:
      - "8080:8080"
#    depends_on:
#      - db
#  database:
#    image: "postgres"
#    ports:
#      - "5434:5434"
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=zoho
##      - POSTGRES_HOST_AUTH_METHOD=trust